version: "3"

volumes:
  pgdata:

services:
  db:
    image: docker.io/postgres:14
    environment:
      POSTGRES_DB: rust-dev-tools
      POSTGRES_USER: rust-dev-tools
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 9999:5432
