name: Job - Update Rust Overlay

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight

jobs:
  update-rust-overlay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake lock --update-input rust-overlay
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update rust-overlay"